### ISSUE TITLE
社区第二次活动 讲师

### ISSUE THREAD

**Issue by William-Sang** [openresty-suzhou/meetup#3]
内容主要是：

以使用者的角度，介绍OR的优势、优点。
通过安装配置，就可以使用到OR的一些特色功能，可能是：限流，权限管理，监控等

@aaashun 推荐个讲师啊

**Comment by William-Sang** [comment]
@aaashun 最好今天能把人定下来，明天白天把 提纲 给到我们，这样我们明晚就能发送活动通告了，进行前期宣传了。

**Comment by aaashun** [comment]
初定我厂提交两个分享, 由组委会review决定:
1. OpenResty在我厂的实践
2. OpenResty1.11.2新特性介绍
